{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "54b90725-397e-40a7-8407-a52b6bf7fafa",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        open down_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close down_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: down_new.mp3\n",
      "Exception in thread Thread-6 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open down_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-7 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-8 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open down_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close down_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: down_new.mp3\n",
      "Exception in thread Thread-9 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open down_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "Exception in thread Thread-14 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-16 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-17 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close down_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: down_new.mp3\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-20 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open down_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close down_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: down_new.mp3\n",
      "Exception in thread Thread-21 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open down_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-22 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-23 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-26 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-28 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-29 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close down_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: down_new.mp3\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-31 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-32 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-34 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "Exception in thread Thread-35 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close down_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: down_new.mp3\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-37 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-38 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close up_new.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: up_new.mp3\n",
      "Exception in thread Thread-40 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "Exception in thread Thread-41 (<lambda>):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel\\ipkernel.py\", line 761, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\Ravi\\AppData\\Local\\Temp\\ipykernel_13880\\554471343.py\", line 26, in <lambda>\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\Ravi\\anaconda3\\Lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play up_new.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import cv2\n",
    "import mediapipe as mp\n",
    "import numpy as np\n",
    "import threading\n",
    "from playsound import playsound\n",
    "from gtts import gTTS\n",
    "\n",
    "# Generate and save audio feedback\n",
    "tts_up = gTTS(\"Up\", lang=\"en\")\n",
    "tts_down = gTTS(\"Down\", lang=\"en\")\n",
    "tts_up.save(\"up_new.mp3\")\n",
    "tts_down.save(\"down_new.mp3\")\n",
    "\n",
    "# Function to calculate angles using 2D coordinates\n",
    "def calculate_angle(a, b, c):\n",
    "    a, b, c = np.array(a), np.array(b), np.array(c)\n",
    "    ab, bc = a - b, c - b\n",
    "\n",
    "    cosine_angle = np.dot(ab, bc) / (np.linalg.norm(ab) * np.linalg.norm(bc))\n",
    "    angle = np.arccos(np.clip(cosine_angle, -1.0, 1.0)) * 180.0 / np.pi\n",
    "    return angle\n",
    "\n",
    "# Function to play sound asynchronously\n",
    "def play_sound(sound_file):\n",
    "    threading.Thread(target=lambda: playsound(sound_file), daemon=True).start()\n",
    "\n",
    "# Initialize MediaPipe Pose\n",
    "mp_drawing, mp_pose = mp.solutions.drawing_utils, mp.solutions.pose\n",
    "\n",
    "# Open camera\n",
    "cap = cv2.VideoCapture(0)\n",
    "counter, stage = 0, None\n",
    "use_right_hand = True  # Default to right hand\n",
    "completed_rep = False\n",
    "\n",
    "# Start pose detection\n",
    "with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:\n",
    "    while cap.isOpened():\n",
    "        ret, frame = cap.read()\n",
    "        if not ret:\n",
    "            break\n",
    "\n",
    "        # Convert image\n",
    "        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "        results = pose.process(image)\n",
    "        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)\n",
    "\n",
    "        try:\n",
    "            if results.pose_landmarks:\n",
    "                landmarks = results.pose_landmarks.landmark\n",
    "\n",
    "                # Extract coordinates based on the selected hand\n",
    "                if use_right_hand:\n",
    "                    shoulder = [landmarks[mp_pose.PoseLandmark.RIGHT_SHOULDER.value].x,\n",
    "                                landmarks[mp_pose.PoseLandmark.RIGHT_SHOULDER.value].y]\n",
    "                    elbow = [landmarks[mp_pose.PoseLandmark.RIGHT_ELBOW.value].x,\n",
    "                             landmarks[mp_pose.PoseLandmark.RIGHT_ELBOW.value].y]\n",
    "                    wrist = [landmarks[mp_pose.PoseLandmark.RIGHT_WRIST.value].x,\n",
    "                             landmarks[mp_pose.PoseLandmark.RIGHT_WRIST.value].y]\n",
    "                else:\n",
    "                    shoulder = [landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].x,\n",
    "                                landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].y]\n",
    "                    elbow = [landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].x,\n",
    "                             landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].y]\n",
    "                    wrist = [landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].x,\n",
    "                             landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].y]\n",
    "\n",
    "                # Calculate the elbow angle\n",
    "                angle = calculate_angle(shoulder, elbow, wrist)\n",
    "                \n",
    "                # Convert coordinates for display\n",
    "                shoulder_coords = tuple(np.multiply(shoulder, [640, 480]).astype(int))\n",
    "                elbow_coords = tuple(np.multiply(elbow, [640, 480]).astype(int))\n",
    "                wrist_coords = tuple(np.multiply(wrist, [640, 480]).astype(int))\n",
    "\n",
    "                # Draw circles on landmarks\n",
    "                cv2.circle(image, shoulder_coords, 5, (0, 255, 0), -1)  # Shoulder\n",
    "                cv2.circle(image, elbow_coords, 5, (255, 0, 0), -1)  # Elbow\n",
    "                cv2.circle(image, wrist_coords, 5, (0, 0, 255), -1)  # Wrist\n",
    "\n",
    "                # Draw lines connecting the shoulder, elbow, and wrist\n",
    "                cv2.line(image, shoulder_coords, elbow_coords, (0, 255, 255), 2)  # Shoulder to Elbow\n",
    "                cv2.line(image, elbow_coords, wrist_coords, (0, 255, 255), 2)  # Elbow to Wrist\n",
    "\n",
    "                # Display angle on screen\n",
    "                cv2.putText(image, f'{int(angle)}°', elbow_coords,\n",
    "                            cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2, cv2.LINE_AA)\n",
    "\n",
    "                # Progress bar (visual indicator of movement)\n",
    "                bar_height = np.interp(angle, (50, 150), (100, 400))\n",
    "                cv2.rectangle(image, (20, 100), (45, 400), (255, 255, 255), 2)\n",
    "                cv2.rectangle(image, (20, int(bar_height)), (45, 400), (0, 255, 0), -1)\n",
    " \n",
    "                # Curl counting logic\n",
    "                if angle > 150 and stage != \"up\":\n",
    "                    stage = \"up\"\n",
    "                    play_sound(\"up_new.mp3\")\n",
    "\n",
    "                if angle < 50 and stage == \"up\":\n",
    "                    stage = \"down\"\n",
    "                    completed_rep = True\n",
    "                    play_sound(\"down_new.mp3\")\n",
    "                \n",
    "                # Hand switching logic\n",
    "                if completed_rep and angle > 150:\n",
    "                    counter += 1\n",
    "                    completed_rep = False\n",
    "                    use_right_hand = not use_right_hand  # Automatically switch hand\n",
    "                    stage = None  # Reset stage\n",
    "\n",
    "            # Display count, stage, and active hand\n",
    "            cv2.putText(image, f'Count: {counter}', (480, 50),\n",
    "                        cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2, cv2.LINE_AA)\n",
    "            cv2.putText(image, f'Stage: {stage}', (480, 80),\n",
    "                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 255), 2, cv2.LINE_AA)\n",
    "            cv2.putText(image, f'Hand: {\"Right\" if use_right_hand else \"Left\"}', (480, 110),\n",
    "                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 0, 0), 2, cv2.LINE_AA)\n",
    "\n",
    "        except Exception as e:\n",
    "            print(f\"Error: {e}\")\n",
    "\n",
    "        # Show the output\n",
    "        cv2.imshow('Virtual Gym Trainer - Single Hand Bicep Curl', image)\n",
    "\n",
    "        # Exit on 'q' press\n",
    "        if cv2.waitKey(10) & 0xFF == ord('q'):\n",
    "            break\n",
    "\n",
    "cap.release()\n",
    "cv2.destroyAllWindows()\n",
    "\n",
    "# Clean up audio files\n",
    "for file in [\"up_new.mp3\", \"down_new.mp3\"]:\n",
    "    if os.path.exists(file):\n",
    "        os.remove(file)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "259f475f-c17a-41e9-be03-88d9c62b1c75",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
